#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COCKPIT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

PROJECT_ROOT="${1:-}"
if [ -z "$PROJECT_ROOT" ]; then
  echo "Usage: bash adapters/valua/run.sh /path/to/Valua" >&2
  exit 1
fi

export COCKPIT_ROOT="$COCKPIT_ROOT"
export AGENTIC_PROJECT_ROOT="$PROJECT_ROOT"
export AGENTIC_ROSTER_PATH="${AGENTIC_ROSTER_PATH:-$PROJECT_ROOT/docs/agentic/agent-bus/ROSTER.json}"

# Safety: Valua adapter should use Valua's project-local roster by default.
# Do not silently fall back to the cockpit bundled roster unless explicitly allowed.
if [ ! -f "$AGENTIC_ROSTER_PATH" ]; then
  if [ "${VALUA_ALLOW_ROSTER_FALLBACK:-0}" = "1" ]; then
    echo "WARN: missing Valua roster at $AGENTIC_ROSTER_PATH; fallback is allowed by VALUA_ALLOW_ROSTER_FALLBACK=1" >&2
  else
    echo "ERROR: missing Valua roster at $AGENTIC_ROSTER_PATH" >&2
    echo "Refusing to start adapter with bundled fallback to avoid cross-project drift." >&2
    echo "If this is a brand-new checkout, scaffold once: node scripts/init-project.mjs --project \"$PROJECT_ROOT\"" >&2
    echo "Or explicitly allow fallback: VALUA_ALLOW_ROSTER_FALLBACK=1 bash adapters/valua/run.sh \"$PROJECT_ROOT\"" >&2
    exit 1
  fi
fi

# Keep Valua’s existing bus/worktree locations by default (operator can override).
export AGENTIC_BUS_DIR="${AGENTIC_BUS_DIR:-$HOME/.codex/valua/agent-bus}"
export AGENTIC_WORKTREES_DIR="${AGENTIC_WORKTREES_DIR:-$HOME/.codex/valua/worktrees/Valua}"

# Valua defaults: keep workers warm and cheap.
export AGENTIC_CODEX_ENGINE="${AGENTIC_CODEX_ENGINE:-app-server}"
export AGENTIC_CODEX_APP_SERVER_PERSIST="${AGENTIC_CODEX_APP_SERVER_PERSIST:-1}"
export AGENTIC_CODEX_WARM_START="${AGENTIC_CODEX_WARM_START:-1}"
export AGENTIC_AUTOPILOT_CONTEXT_MODE="${AGENTIC_AUTOPILOT_CONTEXT_MODE:-auto}"
export AGENTIC_AUTOPILOT_SKILLOPS_GATE="${AGENTIC_AUTOPILOT_SKILLOPS_GATE:-1}"
export AGENTIC_AUTOPILOT_SKILLOPS_GATE_KINDS="${AGENTIC_AUTOPILOT_SKILLOPS_GATE_KINDS:-USER_REQUEST,ORCHESTRATOR_UPDATE}"
export AGENTIC_AUTOPILOT_GUARD_ALLOW_PROTECTED_PUSH="${AGENTIC_AUTOPILOT_GUARD_ALLOW_PROTECTED_PUSH:-0}"
export AGENTIC_AUTOPILOT_GUARD_ALLOW_PR_MERGE="${AGENTIC_AUTOPILOT_GUARD_ALLOW_PR_MERGE:-0}"
export AGENTIC_AUTOPILOT_GUARD_ALLOW_FORCE_PUSH="${AGENTIC_AUTOPILOT_GUARD_ALLOW_FORCE_PUSH:-0}"
export AGENTIC_AUTOPILOT_DELEGATE_GATE="${AGENTIC_AUTOPILOT_DELEGATE_GATE:-1}"
export AGENTIC_AUTOPILOT_SELF_REVIEW_GATE="${AGENTIC_AUTOPILOT_SELF_REVIEW_GATE:-1}"
export AGENTIC_AUTOPILOT_PROACTIVE_STATUS="${AGENTIC_AUTOPILOT_PROACTIVE_STATUS:-1}"
export AGENTIC_AUTOPILOT_SKILL_PROFILE="${AGENTIC_AUTOPILOT_SKILL_PROFILE:-controller}"
export AGENTIC_AUTOPILOT_EXEC_SKILLS="${AGENTIC_AUTOPILOT_EXEC_SKILLS:-valua-exec-agent}"
export AGENTIC_AUTOPILOT_ENABLE_LANG_POLICIES="${AGENTIC_AUTOPILOT_ENABLE_LANG_POLICIES:-0}"
export AGENTIC_AUTOPILOT_SESSION_SCOPE="${AGENTIC_AUTOPILOT_SESSION_SCOPE:-root}"
export AGENTIC_AUTOPILOT_SESSION_ROTATE_TURNS="${AGENTIC_AUTOPILOT_SESSION_ROTATE_TURNS:-40}"
export AGENTIC_CODE_QUALITY_GATE="${AGENTIC_CODE_QUALITY_GATE:-1}"
export AGENTIC_CODE_QUALITY_GATE_KINDS="${AGENTIC_CODE_QUALITY_GATE_KINDS:-USER_REQUEST,ORCHESTRATOR_UPDATE,EXECUTE}"
export AGENTIC_STRICT_COMMIT_SCOPED_GATE="${AGENTIC_STRICT_COMMIT_SCOPED_GATE:-1}"
export AGENTIC_GATE_AUTOREMEDIATE_RETRIES="${AGENTIC_GATE_AUTOREMEDIATE_RETRIES:-2}"
export AGENTIC_EXEC_PREFLIGHT_AUTOCLEAN_DIRTY="${AGENTIC_EXEC_PREFLIGHT_AUTOCLEAN_DIRTY:-0}"
export AGENTIC_CODEX_ENGINE_STRICT="${AGENTIC_CODEX_ENGINE_STRICT:-1}"
export AGENTIC_AUTOPILOT_OPUS_GATE="${AGENTIC_AUTOPILOT_OPUS_GATE:-1}"
export AGENTIC_AUTOPILOT_OPUS_GATE_KINDS="${AGENTIC_AUTOPILOT_OPUS_GATE_KINDS:-USER_REQUEST,PLAN_REQUEST,ORCHESTRATOR_UPDATE,EXECUTE}"
export AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT="${AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT:-opus-consult}"
export AGENTIC_AUTOPILOT_OPUS_GATE_TIMEOUT_MS="${AGENTIC_AUTOPILOT_OPUS_GATE_TIMEOUT_MS:-45000}"
export AGENTIC_AUTOPILOT_OPUS_MAX_ROUNDS="${AGENTIC_AUTOPILOT_OPUS_MAX_ROUNDS:-200}"
export AGENTIC_AUTOPILOT_OPUS_ENFORCE_PREEXEC_BARRIER="${AGENTIC_AUTOPILOT_OPUS_ENFORCE_PREEXEC_BARRIER:-1}"
export AGENTIC_AUTOPILOT_OPUS_WARN_REQUIRES_ACK="${AGENTIC_AUTOPILOT_OPUS_WARN_REQUIRES_ACK:-0}"
export AGENTIC_AUTOPILOT_OPUS_REQUIRE_DECISION_RATIONALE="${AGENTIC_AUTOPILOT_OPUS_REQUIRE_DECISION_RATIONALE:-1}"
export AGENTIC_AUTOPILOT_OPUS_POST_REVIEW="${AGENTIC_AUTOPILOT_OPUS_POST_REVIEW:-1}"
export AGENTIC_AUTOPILOT_OPUS_POST_REVIEW_KINDS="${AGENTIC_AUTOPILOT_OPUS_POST_REVIEW_KINDS:-USER_REQUEST,PLAN_REQUEST,ORCHESTRATOR_UPDATE,EXECUTE}"
export AGENTIC_OPUS_CLAUDE_BIN="${AGENTIC_OPUS_CLAUDE_BIN:-claude}"
export AGENTIC_OPUS_MODEL="${AGENTIC_OPUS_MODEL:-claude-opus-4-6}"
export AGENTIC_OPUS_TIMEOUT_MS="${AGENTIC_OPUS_TIMEOUT_MS:-45000}"
export AGENTIC_OPUS_MAX_RETRIES="${AGENTIC_OPUS_MAX_RETRIES:-0}"
export AGENTIC_OPUS_CACHE="${AGENTIC_OPUS_CACHE:-1}"
export AGENTIC_OPUS_GLOBAL_MAX_INFLIGHT="${AGENTIC_OPUS_GLOBAL_MAX_INFLIGHT:-2}"
export AGENTIC_OPUS_STREAM="${AGENTIC_OPUS_STREAM:-1}"
export AGENTIC_OPUS_STUB_BIN="${AGENTIC_OPUS_STUB_BIN:-}"
export AGENTIC_POLICY_SYNC_ON_START="${AGENTIC_POLICY_SYNC_ON_START:-1}"
export AGENTIC_POLICY_SYNC_SOURCE_REF="${AGENTIC_POLICY_SYNC_SOURCE_REF:-origin/master}"
export VALUA_AUTOPILOT_SKILLOPS_GATE="${VALUA_AUTOPILOT_SKILLOPS_GATE:-$AGENTIC_AUTOPILOT_SKILLOPS_GATE}"
export VALUA_AUTOPILOT_SKILLOPS_GATE_KINDS="${VALUA_AUTOPILOT_SKILLOPS_GATE_KINDS:-$AGENTIC_AUTOPILOT_SKILLOPS_GATE_KINDS}"
export VALUA_AUTOPILOT_GUARD_ALLOW_PROTECTED_PUSH="${VALUA_AUTOPILOT_GUARD_ALLOW_PROTECTED_PUSH:-$AGENTIC_AUTOPILOT_GUARD_ALLOW_PROTECTED_PUSH}"
export VALUA_AUTOPILOT_GUARD_ALLOW_PR_MERGE="${VALUA_AUTOPILOT_GUARD_ALLOW_PR_MERGE:-$AGENTIC_AUTOPILOT_GUARD_ALLOW_PR_MERGE}"
export VALUA_AUTOPILOT_GUARD_ALLOW_FORCE_PUSH="${VALUA_AUTOPILOT_GUARD_ALLOW_FORCE_PUSH:-$AGENTIC_AUTOPILOT_GUARD_ALLOW_FORCE_PUSH}"
export VALUA_AUTOPILOT_DELEGATE_GATE="${VALUA_AUTOPILOT_DELEGATE_GATE:-$AGENTIC_AUTOPILOT_DELEGATE_GATE}"
export VALUA_AUTOPILOT_SELF_REVIEW_GATE="${VALUA_AUTOPILOT_SELF_REVIEW_GATE:-$AGENTIC_AUTOPILOT_SELF_REVIEW_GATE}"
export VALUA_AUTOPILOT_PROACTIVE_STATUS="${VALUA_AUTOPILOT_PROACTIVE_STATUS:-$AGENTIC_AUTOPILOT_PROACTIVE_STATUS}"
export VALUA_AUTOPILOT_SKILL_PROFILE="${VALUA_AUTOPILOT_SKILL_PROFILE:-$AGENTIC_AUTOPILOT_SKILL_PROFILE}"
export VALUA_AUTOPILOT_EXEC_SKILLS="${VALUA_AUTOPILOT_EXEC_SKILLS:-$AGENTIC_AUTOPILOT_EXEC_SKILLS}"
export VALUA_AUTOPILOT_ENABLE_LANG_POLICIES="${VALUA_AUTOPILOT_ENABLE_LANG_POLICIES:-$AGENTIC_AUTOPILOT_ENABLE_LANG_POLICIES}"
export VALUA_AUTOPILOT_SESSION_SCOPE="${VALUA_AUTOPILOT_SESSION_SCOPE:-$AGENTIC_AUTOPILOT_SESSION_SCOPE}"
export VALUA_AUTOPILOT_SESSION_ROTATE_TURNS="${VALUA_AUTOPILOT_SESSION_ROTATE_TURNS:-$AGENTIC_AUTOPILOT_SESSION_ROTATE_TURNS}"
export VALUA_CODE_QUALITY_GATE="${VALUA_CODE_QUALITY_GATE:-$AGENTIC_CODE_QUALITY_GATE}"
export VALUA_CODE_QUALITY_GATE_KINDS="${VALUA_CODE_QUALITY_GATE_KINDS:-$AGENTIC_CODE_QUALITY_GATE_KINDS}"
export VALUA_STRICT_COMMIT_SCOPED_GATE="${VALUA_STRICT_COMMIT_SCOPED_GATE:-$AGENTIC_STRICT_COMMIT_SCOPED_GATE}"
export VALUA_GATE_AUTOREMEDIATE_RETRIES="${VALUA_GATE_AUTOREMEDIATE_RETRIES:-$AGENTIC_GATE_AUTOREMEDIATE_RETRIES}"
export VALUA_EXEC_PREFLIGHT_AUTOCLEAN_DIRTY="${VALUA_EXEC_PREFLIGHT_AUTOCLEAN_DIRTY:-$AGENTIC_EXEC_PREFLIGHT_AUTOCLEAN_DIRTY}"
export VALUA_AUTOPILOT_OPUS_GATE="${VALUA_AUTOPILOT_OPUS_GATE:-$AGENTIC_AUTOPILOT_OPUS_GATE}"
export VALUA_AUTOPILOT_OPUS_GATE_KINDS="${VALUA_AUTOPILOT_OPUS_GATE_KINDS:-$AGENTIC_AUTOPILOT_OPUS_GATE_KINDS}"
export VALUA_AUTOPILOT_OPUS_CONSULT_AGENT="${VALUA_AUTOPILOT_OPUS_CONSULT_AGENT:-$AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT}"
export VALUA_AUTOPILOT_OPUS_GATE_TIMEOUT_MS="${VALUA_AUTOPILOT_OPUS_GATE_TIMEOUT_MS:-$AGENTIC_AUTOPILOT_OPUS_GATE_TIMEOUT_MS}"
export VALUA_AUTOPILOT_OPUS_MAX_ROUNDS="${VALUA_AUTOPILOT_OPUS_MAX_ROUNDS:-$AGENTIC_AUTOPILOT_OPUS_MAX_ROUNDS}"
export VALUA_AUTOPILOT_OPUS_ENFORCE_PREEXEC_BARRIER="${VALUA_AUTOPILOT_OPUS_ENFORCE_PREEXEC_BARRIER:-$AGENTIC_AUTOPILOT_OPUS_ENFORCE_PREEXEC_BARRIER}"
export VALUA_AUTOPILOT_OPUS_WARN_REQUIRES_ACK="${VALUA_AUTOPILOT_OPUS_WARN_REQUIRES_ACK:-$AGENTIC_AUTOPILOT_OPUS_WARN_REQUIRES_ACK}"
export VALUA_AUTOPILOT_OPUS_REQUIRE_DECISION_RATIONALE="${VALUA_AUTOPILOT_OPUS_REQUIRE_DECISION_RATIONALE:-$AGENTIC_AUTOPILOT_OPUS_REQUIRE_DECISION_RATIONALE}"
export VALUA_AUTOPILOT_OPUS_POST_REVIEW="${VALUA_AUTOPILOT_OPUS_POST_REVIEW:-$AGENTIC_AUTOPILOT_OPUS_POST_REVIEW}"
export VALUA_AUTOPILOT_OPUS_POST_REVIEW_KINDS="${VALUA_AUTOPILOT_OPUS_POST_REVIEW_KINDS:-$AGENTIC_AUTOPILOT_OPUS_POST_REVIEW_KINDS}"
export VALUA_OPUS_CLAUDE_BIN="${VALUA_OPUS_CLAUDE_BIN:-$AGENTIC_OPUS_CLAUDE_BIN}"
export VALUA_OPUS_MODEL="${VALUA_OPUS_MODEL:-$AGENTIC_OPUS_MODEL}"
export VALUA_OPUS_TIMEOUT_MS="${VALUA_OPUS_TIMEOUT_MS:-$AGENTIC_OPUS_TIMEOUT_MS}"
export VALUA_OPUS_MAX_RETRIES="${VALUA_OPUS_MAX_RETRIES:-$AGENTIC_OPUS_MAX_RETRIES}"
export VALUA_OPUS_CACHE="${VALUA_OPUS_CACHE:-$AGENTIC_OPUS_CACHE}"
export VALUA_OPUS_GLOBAL_MAX_INFLIGHT="${VALUA_OPUS_GLOBAL_MAX_INFLIGHT:-$AGENTIC_OPUS_GLOBAL_MAX_INFLIGHT}"
export VALUA_OPUS_STREAM="${VALUA_OPUS_STREAM:-$AGENTIC_OPUS_STREAM}"
export VALUA_OPUS_STUB_BIN="${VALUA_OPUS_STUB_BIN:-$AGENTIC_OPUS_STUB_BIN}"
export VALUA_POLICY_SYNC_ON_START="${VALUA_POLICY_SYNC_ON_START:-$AGENTIC_POLICY_SYNC_ON_START}"
export VALUA_POLICY_SYNC_SOURCE_REF="${VALUA_POLICY_SYNC_SOURCE_REF:-$AGENTIC_POLICY_SYNC_SOURCE_REF}"
export VALUA_CODEX_ENGINE_STRICT="${VALUA_CODEX_ENGINE_STRICT:-$AGENTIC_CODEX_ENGINE_STRICT}"

# Orchestrator digests: compact to autopilot by default (human digest optional/compact).
export AGENTIC_ORCH_AUTOPILOT_DIGEST_MODE="${AGENTIC_ORCH_AUTOPILOT_DIGEST_MODE:-compact}"
export AGENTIC_ORCH_FORWARD_TO_DADDY="${AGENTIC_ORCH_FORWARD_TO_DADDY:-0}"
export AGENTIC_ORCH_DADDY_DIGEST_MODE="${AGENTIC_ORCH_DADDY_DIGEST_MODE:-compact}"

# Reduce Codex rollout/index reconciliation noise by isolating Codex state per agent.
export AGENTIC_CODEX_HOME_MODE="${AGENTIC_CODEX_HOME_MODE:-agent}"

# In adapter mode, Codex runs with cwd=$PROJECT_ROOT, so skills should come from the Valua repo
# (e.g. `.codex/skills/valua-daddy-chat-io`). Default the interactive chat boot prompt accordingly.
export VALUA_CODEX_CHAT_BOOT_PROMPT="${VALUA_CODEX_CHAT_BOOT_PROMPT:-\$valua-daddy-chat-io}"

# Valua-specific observer policy: only monitor active PR range.
# This prevents older legacy PR threads from re-entering the automation loop.
export AGENTIC_PR_OBSERVER_MIN_PR="${AGENTIC_PR_OBSERVER_MIN_PR:-82}"

is_enabled() {
  local raw
  raw="$(echo "${1:-}" | tr '[:upper:]' '[:lower:]' | xargs)"
  case "$raw" in
    1|true|yes|on|auto) return 0 ;;
    *) return 1 ;;
  esac
}

if is_enabled "${AGENTIC_AUTOPILOT_OPUS_GATE:-0}" || is_enabled "${AGENTIC_AUTOPILOT_OPUS_POST_REVIEW:-0}"; then
  if ! AGENTIC_PROJECT_ROOT="$AGENTIC_PROJECT_ROOT" \
       COCKPIT_ROOT="$COCKPIT_ROOT" \
       AGENTIC_ROSTER_PATH="$AGENTIC_ROSTER_PATH" \
       AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT="$AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT" \
       AGENTIC_OPUS_PROMPT_DIR="${AGENTIC_OPUS_PROMPT_DIR:-}" \
       AGENTIC_OPUS_PROVIDER_SCHEMA_PATH="${AGENTIC_OPUS_PROVIDER_SCHEMA_PATH:-}" \
       node <<'NODE'
const fs = require('fs');
const path = require('path');

function readString(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function uniquePaths(paths) {
  const out = [];
  const seen = new Set();
  for (const raw of paths) {
    const s = readString(raw);
    if (!s) continue;
    const resolved = path.resolve(s);
    if (seen.has(resolved)) continue;
    seen.add(resolved);
    out.push(resolved);
  }
  return out;
}

const rosterPath = readString(process.env.AGENTIC_ROSTER_PATH);
const projectRoot = readString(process.env.AGENTIC_PROJECT_ROOT);
const cockpitRoot = readString(process.env.COCKPIT_ROOT);
const consultAgent = readString(process.env.AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT) || 'opus-consult';

if (!rosterPath || !fs.existsSync(rosterPath)) {
  console.error(`ERROR: OPUS preflight failed: roster path not found: ${rosterPath || '(empty)'}`);
  process.exit(2);
}
const roster = JSON.parse(fs.readFileSync(rosterPath, 'utf8'));
const agents = Array.isArray(roster.agents) ? roster.agents : [];
const consult = agents.find((agent) => readString(agent && agent.name) === consultAgent);
if (!consult) {
  console.error(`ERROR: OPUS preflight failed: consult agent "${consultAgent}" missing from roster ${rosterPath}`);
  process.exit(2);
}
if (readString(consult.kind) !== 'codex-worker') {
  console.error(`ERROR: OPUS preflight failed: consult agent "${consultAgent}" must be kind=codex-worker (got "${readString(consult.kind) || 'unknown'}")`);
  process.exit(2);
}

const promptDirOverride = readString(process.env.AGENTIC_OPUS_PROMPT_DIR);
const promptDirCandidates = uniquePaths([
  promptDirOverride,
  projectRoot ? path.join(projectRoot, '.codex', 'opus') : '',
  cockpitRoot ? path.join(cockpitRoot, '.codex', 'opus') : '',
]);
const promptDir = promptDirCandidates.find((dir) => (
  fs.existsSync(path.join(dir, 'OPUS_INSTRUCTIONS.md')) &&
  fs.existsSync(path.join(dir, 'OPUS_SKILLS.md'))
));
if (!promptDir) {
  console.error(`ERROR: OPUS preflight failed: prompt assets missing. searched: ${promptDirCandidates.join(', ') || '(none)'}`);
  process.exit(2);
}

const providerSchemaOverride = readString(process.env.AGENTIC_OPUS_PROVIDER_SCHEMA_PATH);
const providerSchemaCandidates = uniquePaths([
  providerSchemaOverride,
  projectRoot ? path.join(projectRoot, 'docs', 'agentic', 'agent-bus', 'OPUS_CONSULT.provider.schema.json') : '',
  cockpitRoot ? path.join(cockpitRoot, 'docs', 'agentic', 'agent-bus', 'OPUS_CONSULT.provider.schema.json') : '',
]);
const providerSchemaPath = providerSchemaCandidates.find((candidate) => fs.existsSync(candidate));
if (!providerSchemaPath) {
  console.error(`ERROR: OPUS preflight failed: provider schema missing. searched: ${providerSchemaCandidates.join(', ') || '(none)'}`);
  process.exit(2);
}
NODE
  then
    echo "Refusing to start with broken OPUS consult wiring." >&2
    echo "Remediation: add consult agent \"$AGENTIC_AUTOPILOT_OPUS_CONSULT_AGENT\" to roster and ensure prompt/schema assets exist in project or cockpit root." >&2
    exit 1
  fi
fi

exec bash "$COCKPIT_ROOT/scripts/tmux/cockpit.sh" up
